#!/usr/bin/env python3
"""Generates src/kernels_cuda/dequant_iq_tables.cuh from src/dequant_iq_tables.rs.

src/dequant_iq_tables.rs is itself a byte-for-byte transcription of the IQ
codebook/lookup tables in upstream ggml-org/llama.cpp's `ggml/src/ggml-common.h`
(see that file's own doc comment). Rather than re-transcribing ~4000 lines a
second time from the C header for the CUDA on-device dequant kernels
(src/kernels_cuda/dequant.cu), this script mechanically re-emits the same
values as CUDA `__constant__` arrays from the already-verified Rust source --
one generator, one source of truth, no second opportunity for a transcription
typo to diverge between the host and device paths.

Run from the repo root: `python3 scripts/gen_iq_tables.py`.
"""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_RS = REPO_ROOT / "src" / "dequant_iq_tables.rs"
OUT_CUH = REPO_ROOT / "src" / "kernels_cuda" / "dequant_iq_tables.cuh"

RUST_TO_C_TYPE = {
    "u8": "unsigned char",
    "u16": "unsigned short",
    "u32": "unsigned int",
    "u64": "unsigned long long",
    "i8": "signed char",
}

ARRAY_RE = re.compile(
    r"pub\(crate\) static (?P<name>\w+): \[(?P<ty>\w+); (?P<len>\d+)\] = \[(?P<body>.*?)\];",
    re.DOTALL,
)


def format_value(raw: str, rust_ty: str) -> str:
    v = raw.strip()
    if not v:
        return v
    if rust_ty == "i8":
        # Rust negative-literal ints port straight over; C `signed char`
        # holds the same range.
        return v
    if rust_ty == "u64":
        # Rust hex literals like 0x0808...08 have no suffix; C needs ULL so
        # values above UINT32_MAX aren't silently truncated/misinterpreted.
        return v + "ULL"
    if rust_ty == "u32":
        return v + "U"
    return v


def main() -> None:
    text = SRC_RS.read_text(encoding="utf-8")
    arrays = list(ARRAY_RE.finditer(text))
    if not arrays:
        raise SystemExit(f"no `pub(crate) static NAME: [TYPE; LEN] = [...]` arrays found in {SRC_RS}")

    lines = [
        "// Generated by scripts/gen_iq_tables.py from src/dequant_iq_tables.rs -- do not",
        "// hand-edit. Re-run the script if src/dequant_iq_tables.rs changes.",
        "//",
        "// Codebook/lookup tables for the IQ-family GGML quant types' on-device dequant",
        "// kernels (src/kernels_cuda/dequant.cu). Same values as the host path",
        "// (src/dequant_iq_tables.rs), which are themselves a byte-for-byte transcription",
        "// of upstream ggml-org/llama.cpp's `ggml/src/ggml-common.h` -- see that file's",
        "// doc comment for provenance.",
        "",
        "#pragma once",
        "",
    ]

    for m in arrays:
        name = m.group("name")
        rust_ty = m.group("ty")
        length = m.group("len")
        body = m.group("body")
        c_ty = RUST_TO_C_TYPE[rust_ty]

        values = [v.strip() for v in body.split(",")]
        values = [v for v in values if v]
        if len(values) != int(length):
            raise SystemExit(
                f"{name}: expected {length} elements, parsed {len(values)}"
            )
        formatted = [format_value(v, rust_ty) for v in values]

        lines.append(f"__constant__ {c_ty} {name}[{length}] = {{")
        # 12 values per line keeps line length reasonable for both narrow
        # (u8/i8) and wide (u64) element types.
        per_line = 12
        for i in range(0, len(formatted), per_line):
            chunk = ", ".join(formatted[i : i + per_line])
            lines.append(f"    {chunk},")
        lines.append("};")
        lines.append("")

    OUT_CUH.parent.mkdir(parents=True, exist_ok=True)
    OUT_CUH.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_CUH} ({len(arrays)} arrays)")


if __name__ == "__main__":
    main()
