/* coldstart-infer C-FFI header.
 *
 * Generated by cbindgen from src/ffi.rs -- that file is the source of
 * truth; see its module doc comment and README.md's "Phase 4 --
 * Embeddability" section for scope. Do not edit this file by hand; changes
 * will be overwritten the next time it's regenerated. */

#ifndef COLDSTART_INFER_H
#define COLDSTART_INFER_H

/* Warning: autogenerated by cbindgen from src/ffi.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a loaded model, obtained from `coldstart_load` and freed
 * with `coldstart_free`. C callers only ever see a pointer to this type --
 * never its layout.
 */
typedef struct ColdstartModel ColdstartModel;

/**
 * Output of `coldstart_generate`. `token_ids`/`text` are heap buffers owned
 * by this crate -- free them (and reset this struct to all-zero/NULL) with
 * `coldstart_free_generate_result`, never with the C caller's own
 * `free`/`libc::free`.
 */
typedef struct {
    /**
     * Array of `num_tokens` generated token ids.
     */
    uint32_t *token_ids;
    uintptr_t num_tokens;
    /**
     * NUL-terminated UTF-8 decoded text of the generated tokens.
     */
    char *text;
} ColdstartGenerateResult;

/**
 * Returns the last error message set by this thread's most recent failing
 * `coldstart_*` call, or NULL if the most recent call succeeded (or none
 * has run yet on this thread). The returned pointer is valid only until the
 * next `coldstart_*` call on this thread -- copy it if it needs to outlive
 * that.
 */
const char *coldstart_last_error(void);

/**
 * Loads a GGUF model from `gguf_path` onto CUDA device 0, optionally
 * applying a llama.cpp-format LoRA adapter from `lora_path` first (pass
 * NULL to skip -- see `Model::apply_lora`'s doc comment in `model.rs` for
 * which architectures/tensors are accepted; DeepSeek-V2/V3 MLA rejects any
 * LoRA path).
 *
 * Returns an opaque handle to free with `coldstart_free`, or NULL on
 * failure (call `coldstart_last_error` for why). `gguf_path` must be
 * non-NULL; `lora_path` may be NULL. Both, when non-NULL, must be
 * NUL-terminated UTF-8 C strings; this function does not take ownership of
 * either and they may be freed by the caller as soon as it returns.
 */
ColdstartModel *coldstart_load(const char *gguf_path, const char *lora_path);

/**
 * Runs a forward pass and up to `max_new_tokens` greedy-decoded generation
 * steps (feeding each generated id back in, stopping early on the
 * tokenizer's EOS) starting fresh from `prompt` -- the same behavior as
 * `qwen3_coldstart <gguf> <prompt> --max-tokens <max_new_tokens>` with
 * neither `--export-kv` nor `--import-kv`. Phase 3's `--import-kv` resume
 * path is not exposed through this FFI round (see module doc comment).
 *
 * `handle` must come from `coldstart_load` and not have been freed yet.
 * `prompt` must be a non-NULL, NUL-terminated UTF-8 C string; `max_new_tokens`
 * must be at least 1. `out` must be a non-NULL pointer to a
 * `ColdstartGenerateResult` the caller owns (its initial contents are
 * ignored, not read).
 *
 * On success, fills `*out` and returns 0 -- the caller must eventually pass
 * `out` to `coldstart_free_generate_result`. On failure, leaves `*out`
 * untouched and returns -1 (call `coldstart_last_error` for why).
 */
int coldstart_generate(ColdstartModel *handle,
                       const char *prompt,
                       uintptr_t max_new_tokens,
                       ColdstartGenerateResult *out);

/**
 * Frees the buffers inside a `ColdstartGenerateResult` previously filled by
 * `coldstart_generate`, and zeroes the struct out. Safe to call on a
 * zeroed/all-NULL struct (no-op), and safe to call more than once on the
 * same struct for that reason -- but never on two different copies of the
 * same non-zeroed struct (double free).
 */
void coldstart_free_generate_result(ColdstartGenerateResult *result);

/**
 * Frees a handle obtained from `coldstart_load`. Safe to call with NULL
 * (no-op). The handle must not be used again afterward.
 */
void coldstart_free(ColdstartModel *handle);

#endif  /* COLDSTART_INFER_H */
