/* Reflex (reflex-engine) C-FFI header.
 *
 * Generated by cbindgen from src/ffi.rs -- that file is the source of
 * truth; see its module doc comment and README.md's "Embeddability"
 * section for scope. Do not edit this file by hand; changes will be
 * overwritten the next time it's regenerated. */

#ifndef REFLEX_ENGINE_H
#define REFLEX_ENGINE_H

/* Warning: autogenerated by cbindgen from src/ffi.rs. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a loaded model, obtained from `reflex_load` and freed
 * with `reflex_free`. C callers only ever see a pointer to this type --
 * never its layout.
 */
typedef struct ReflexModel ReflexModel;

/**
 * Output of `reflex_generate`. `token_ids`/`text` are heap buffers owned
 * by this crate -- free them (and reset this struct to all-zero/NULL) with
 * `reflex_free_generate_result`, never with the C caller's own
 * `free`/`libc::free`.
 */
typedef struct {
    /**
     * Array of `num_tokens` generated token ids.
     */
    uint32_t *token_ids;
    uintptr_t num_tokens;
    /**
     * NUL-terminated UTF-8 decoded text of the generated tokens.
     */
    char *text;
} ReflexGenerateResult;

/**
 * One candidate's scored result within a `ReflexSystem1Result`. `text`/
 * `token_ids` are heap buffers owned by this crate, freed only via the
 * outer struct's `reflex_free_system1_result` -- never individually.
 * `score`/`probability` are relative to the candidate set in this one
 * call, not vocab-normalized log-probabilities -- see
 * `crate::model::Model::system1_evaluate`'s doc comment.
 */
typedef struct {
    char *text;
    uint32_t *token_ids;
    uintptr_t num_token_ids;
    float score;
    float probability;
} ReflexSystem1CandidateResult;

/**
 * Output of `reflex_system1_evaluate`. `candidates` is a heap buffer
 * owned by this crate -- free it (and reset this struct to all-zero/NULL)
 * with `reflex_free_system1_result`, never with the C caller's own
 * `free`/`libc::free`. `entropy` (Shannon entropy, bits, of the `probability`
 * distribution across `candidates`) is a single confidence/escalation signal
 * alongside the per-candidate probabilities -- see
 * `crate::model::System1Response::entropy`'s doc comment.
 */
typedef struct {
    ReflexSystem1CandidateResult *candidates;
    uintptr_t num_candidates;
    float entropy;
} ReflexSystem1Result;

/**
 * Returns the last error message set by this thread's most recent failing
 * `reflex_*` call, or NULL if the most recent call succeeded (or none
 * has run yet on this thread). The returned pointer is valid only until the
 * next `reflex_*` call on this thread -- copy it if it needs to outlive
 * that.
 */
const char *reflex_last_error(void);

/**
 * Loads a GGUF model from `gguf_path` onto CUDA device 0, optionally
 * applying a llama.cpp-format LoRA adapter from `lora_path` first (pass
 * NULL to skip -- see `Model::apply_lora`'s doc comment in `model.rs` for
 * which architectures/tensors are accepted; DeepSeek-V2/V3 MLA rejects any
 * LoRA path).
 *
 * Returns an opaque handle to free with `reflex_free`, or NULL on
 * failure (call `reflex_last_error` for why). `gguf_path` must be
 * non-NULL; `lora_path` may be NULL. Both, when non-NULL, must be
 * NUL-terminated UTF-8 C strings; this function does not take ownership of
 * either and they may be freed by the caller as soon as it returns.
 *
 * # Safety
 * `gguf_path` and, when non-NULL, `lora_path` must each point to a valid
 * NUL-terminated C string readable for the duration of this call.
 */
ReflexModel *reflex_load(const char *gguf_path, const char *lora_path);

/**
 * Runs a forward pass and up to `max_new_tokens` greedy-decoded generation
 * steps (feeding each generated id back in, stopping early on the
 * tokenizer's EOS) starting fresh from `prompt` -- the same behavior as
 * `reflex generate <gguf> <prompt> --max-tokens <max_new_tokens>` with
 * neither `--export-kv` nor `--import-kv`. Phase 3's `--import-kv` resume
 * path is not exposed through this FFI round (see module doc comment).
 *
 * `handle` must come from `reflex_load` and not have been freed yet.
 * `prompt` must be a non-NULL, NUL-terminated UTF-8 C string; `max_new_tokens`
 * must be at least 1. `out` must be a non-NULL pointer to a
 * `ReflexGenerateResult` the caller owns (its initial contents are
 * ignored, not read).
 *
 * On success, fills `*out` and returns 0 -- the caller must eventually pass
 * `out` to `reflex_free_generate_result`. On failure, leaves `*out`
 * untouched and returns -1 (call `reflex_last_error` for why).
 *
 * # Safety
 * `handle` must be a live pointer from `reflex_load`, not yet freed, and not
 * used concurrently from another thread. `prompt` must point to a valid
 * NUL-terminated C string readable for the duration of this call. `out`
 * must point to writable, properly aligned `ReflexGenerateResult` storage.
 */
int reflex_generate(ReflexModel *handle,
                    const char *prompt,
                    uintptr_t max_new_tokens,
                    ReflexGenerateResult *out);

/**
 * Frees the buffers inside a `ReflexGenerateResult` previously filled by
 * `reflex_generate`, and zeroes the struct out. Safe to call on a
 * zeroed/all-NULL struct (no-op), and safe to call more than once on the
 * same struct for that reason -- but never on two different copies of the
 * same non-zeroed struct (double free).
 *
 * # Safety
 * `result`, if non-NULL, must point to a `ReflexGenerateResult` either
 * zeroed or previously filled by `reflex_generate` and not yet freed.
 */
void reflex_free_generate_result(ReflexGenerateResult *result);

/**
 * Runs System1 (single-pass, non-autoregressive candidate scoring, see
 * `crate::model::Model::system1_evaluate`'s doc comment) against `prompt`
 * for each of `num_candidates` candidate strings in `candidate_texts`. No
 * argmax-then-feedback decode loop runs -- single-token candidates are
 * scored in one batched gather-GEMV, multi-token candidates via a short
 * teacher-forced continuation. Dense/MoE Qwen3 models only; hybrid Qwen3.5
 * and DeepSeek-V2/V3 MLA are rejected with an error (call
 * `reflex_last_error` for why).
 *
 * `handle` must come from `reflex_load` and not have been freed yet.
 * `prompt` must be a non-NULL, NUL-terminated UTF-8 C string. `candidate_texts`
 * must be a non-NULL pointer to `num_candidates` non-NULL, NUL-terminated
 * UTF-8 C string pointers, with `num_candidates` at least 1. `temperature`
 * (`1.0` = no-op) is passed through to the calibrated `probability` field
 * on each result. `out` must be a non-NULL pointer to a
 * `ReflexSystem1Result` the caller owns (its initial contents are
 * ignored, not read).
 *
 * On success, fills `*out` and returns 0 -- the caller must eventually pass
 * `out` to `reflex_free_system1_result`. On failure, leaves `*out`
 * untouched and returns -1 (call `reflex_last_error` for why).
 *
 * # Safety
 * `handle` must be a live pointer from `reflex_load`, not yet freed, and not
 * used concurrently from another thread. `prompt` must point to a valid
 * NUL-terminated C string readable for the duration of this call.
 * `candidate_texts` must point to `num_candidates` valid, non-NULL,
 * NUL-terminated C string pointers. `out` must point to writable, properly
 * aligned `ReflexSystem1Result` storage.
 */
int reflex_system1_evaluate(ReflexModel *handle,
                            const char *prompt,
                            const char *const *candidate_texts,
                            uintptr_t num_candidates,
                            float temperature,
                            ReflexSystem1Result *out);

/**
 * Frees the buffers inside a `ReflexSystem1Result` previously filled by
 * `reflex_system1_evaluate` (including every candidate's own `text`/
 * `token_ids`), and zeroes the struct out. Safe to call on a zeroed/
 * all-NULL struct (no-op), and safe to call more than once on the same
 * struct for that reason -- but never on two different copies of the same
 * non-zeroed struct (double free).
 *
 * # Safety
 * `result`, if non-NULL, must point to a `ReflexSystem1Result` either
 * zeroed or previously filled by `reflex_system1_evaluate` and not yet
 * freed.
 */
void reflex_free_system1_result(ReflexSystem1Result *result);

/**
 * Frees a handle obtained from `reflex_load`. Safe to call with NULL
 * (no-op). The handle must not be used again afterward.
 *
 * # Safety
 * `handle`, if non-NULL, must be a live pointer from `reflex_load` not yet
 * freed, and must not be in use on any other thread.
 */
void reflex_free(ReflexModel *handle);

#endif  /* REFLEX_ENGINE_H */
